import { apiClient } from '../api-client';
import { getApiErrorMessage } from '../api-errors';

export interface CarCompatibility {
  carId: string;
  carBrand: string;
  carModel: string;
  carYearFrom: number | null;
  carYearTo: number | null;
  isCompatible: boolean;
  notes: string | null;
}

export interface ProductSpec {
  isFilterable: boolean;
  sortOrder: number;
  type: string;
  unit: string | null;
  value: string;
}

export interface ProductSpecs {
  [key: string]: ProductSpec;
}

export interface ProductTranslation {
  languageCode: string;
  name: string;
  description: string | null;
  shortDescription: string | null;
  slug: string;
  metaTitle: string | null;
  metaDescription: string | null;
  tags: string[];
}

export interface CategoryInfo {
  id: string;
  name: string;
  slug: string;
  [key: string]: any;
}

export interface Product {
  id: string;
  itemCode: string;
  storeId: string;
  categoryId: string | null;
  subCategoryId: string | null;
  isActive: boolean;
  price: number;
  stockQuantity: number;
  createdAt: string;
  updatedAt: string;
  mainImage: string | null;
  secondaryImage: string | null;
  images: string[];
  in_favs: boolean;
  brand: string | null;
  carCompatibility: CarCompatibility[];
  specs: {
    [languageCode: string]: ProductSpecs;
  };
  translations: ProductTranslation[];
  variants?: ProductVariant[];
  category?: CategoryInfo;
  subCategory?: CategoryInfo;
  // Computed fields for display
  name?: string;
  description?: string;
  color?: string;
  material?: string;
  size?: string;
  carInfo?: string;
}

export interface ProductListParams {
  storeId: string;
  languageId: string;
  categoryId?: string;
  subCategoryId?: string;
  productTypeId?: string;
  search?: string;
  page?: number;
  limit?: number;
  carBrand?: string;
  carModel?: string;
  // New parameters for year-range based filtering
  carId?: string;
  carYear?: number;
}

export interface ProductListResponse {
  data: Product[];
  meta: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
    hasNext: boolean;
    hasPrev: boolean;
  };
}

export interface SpecificationTranslation {
  languageId: string;
  specValue: string;
}

export interface Specification {
  specKey: string;
  specValue: string;
  specUnit?: string;
  specType: 'text' | 'number' | 'boolean' | 'date';
  isFilterable?: boolean;
  translations?: SpecificationTranslation[];
}

export interface ProductVariant {
  id?: string;
  sku?: string; // Auto-generated by backend
  size: string | null;
  color: string | null;
  priceAdjustment: number;
  stockQuantity: number;
  mainImage: string | null;
  images: string[];
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateProductRequest {
  itemCode: string;
  storeId: string;
  categoryId: string;
  subCategoryId?: string;
  price: number;
  stockQuantity: number;
  brand?: string;
  size?: string;
  mainImage?: string;
  secondaryImage?: string;
  images?: string[];
  isActive?: boolean;
  translations: {
    languageId: string;
    name: string;
    description?: string;
    shortDescription?: string;
    metaTitle?: string;
    metaDescription?: string;
    tags?: string[];
    slug?: string;
  }[];
  specifications?: Specification[];
  carCompatibility?: {
    carId: string;
    isCompatible?: boolean;
    notes?: string;
  }[];
  variants?: ProductVariant[];
}

export interface UpdateProductRequest extends Partial<CreateProductRequest> {
  main_image?: string | null;
  secondary_image?: string | null;
}

export function sumVariantStock(variants: ProductVariant[]): number {
  return variants
    .filter((v) => v.isActive !== false)
    .reduce((sum, v) => sum + (v.stockQuantity || 0), 0);
}

export function getEffectiveStockQuantity(
  product: Pick<Product, 'stockQuantity' | 'variants'>,
): number {
  if (product.variants?.length) {
    return sumVariantStock(product.variants);
  }
  return product.stockQuantity;
}

const normalizeImageUrl = (url: string) => url.split('?')[0];

export function buildProductImageRemovalPayload(
  product: Pick<Product, 'mainImage' | 'secondaryImage' | 'images'>,
  imageType: 'main' | 'secondary' | 'gallery',
  imageUrl: string,
): UpdateProductRequest {
  const galleryImages = product.images || [];
  const mainUrl = product.mainImage ? normalizeImageUrl(product.mainImage) : null;
  const secondaryUrl = product.secondaryImage
    ? normalizeImageUrl(product.secondaryImage)
    : null;

  const filteredGallery = galleryImages.filter((img) => {
    const normalized = normalizeImageUrl(img);
    return normalized !== mainUrl && normalized !== secondaryUrl;
  });

  if (imageType === 'main') {
    return {
      mainImage: null,
      main_image: null,
      images: filteredGallery,
    };
  }

  if (imageType === 'secondary') {
    return {
      secondaryImage: null,
      secondary_image: null,
      images: filteredGallery,
    };
  }

  const targetUrl = normalizeImageUrl(imageUrl);
  return {
    images: filteredGallery.filter((img) => normalizeImageUrl(img) !== targetUrl),
  };
}

export function wasProductImageRemoved(
  product: Pick<Product, 'mainImage' | 'secondaryImage' | 'images'>,
  imageType: 'main' | 'secondary' | 'gallery',
  imageUrl: string,
): boolean {
  if (imageType === 'main') {
    return !product.mainImage;
  }

  if (imageType === 'secondary') {
    return !product.secondaryImage;
  }

  const targetUrl = normalizeImageUrl(imageUrl);
  return !(product.images || []).some(
    (img) => normalizeImageUrl(img) === targetUrl,
  );
}

type ProductImages = Pick<Product, 'mainImage' | 'secondaryImage' | 'images'>;

function buildGalleryAfterPromotion(
  product: ProductImages,
  promotedUrl: string,
  demotedUrl: string | null | undefined,
  reservedUrls: Array<string | null | undefined>,
): string[] {
  const reserved = new Set(
    [promotedUrl, ...reservedUrls]
      .filter(Boolean)
      .map((url) => normalizeImageUrl(url as string)),
  );
  const gallery: string[] = [];
  const seen = new Set<string>();

  const addToGallery = (url: string | null | undefined) => {
    if (!url) return;
    const normalized = normalizeImageUrl(url);
    if (reserved.has(normalized) || seen.has(normalized)) return;
    seen.add(normalized);
    gallery.push(url);
  };

  for (const img of product.images || []) {
    addToGallery(img);
  }

  addToGallery(demotedUrl);

  return gallery;
}

export function buildSetPrimaryImagePayload(
  product: ProductImages,
  imageUrl: string,
): UpdateProductRequest {
  return {
    mainImage: imageUrl,
    main_image: imageUrl,
    images: buildGalleryAfterPromotion(
      product,
      imageUrl,
      product.mainImage,
      [product.secondaryImage],
    ),
  };
}

export function buildSetSecondaryImagePayload(
  product: ProductImages,
  imageUrl: string,
): UpdateProductRequest {
  return {
    secondaryImage: imageUrl,
    secondary_image: imageUrl,
    images: buildGalleryAfterPromotion(
      product,
      imageUrl,
      product.secondaryImage,
      [product.mainImage],
    ),
  };
}

function parseProductListResponse(
  body: any,
  params: ProductListParams,
): ProductListResponse {
  if (body?.success === false) {
    throw new Error(body?.error?.message || 'Failed to fetch products');
  }

  const payload = body?.data;
  const page = params.page ?? 1;
  const limit = params.limit ?? 20;

  if (Array.isArray(payload)) {
    const meta = body?.meta ?? {};
    return {
      data: payload,
      meta: {
        total: meta.total ?? payload.length,
        page: meta.page ?? page,
        limit: meta.limit ?? limit,
        totalPages: meta.totalPages ?? 1,
        hasNext: meta.hasNext ?? false,
        hasPrev: meta.hasPrev ?? false,
      },
    };
  }

  if (payload && typeof payload === 'object') {
    const products =
      payload.products ??
      payload.items ??
      (Array.isArray(payload.data) ? payload.data : []);

    const pagination = payload.pagination ?? payload.meta ?? body?.meta ?? {};
    const total =
      pagination.total ??
      pagination.totalCount ??
      payload.total ??
      products.length;

    return {
      data: products,
      meta: {
        total,
        page: pagination.page ?? payload.page ?? page,
        limit: pagination.limit ?? payload.limit ?? limit,
        totalPages:
          pagination.totalPages ??
          payload.totalPages ??
          Math.max(1, Math.ceil(total / (limit || 1))),
        hasNext: pagination.hasNext ?? payload.hasNext ?? false,
        hasPrev: pagination.hasPrev ?? payload.hasPrev ?? page > 1,
      },
    };
  }

  throw new Error('Unexpected products API response format');
}

class ProductService {
  /**
   * List products (admin)
   * GET /api/admin/products
   */
  async listProducts(params: ProductListParams): Promise<ProductListResponse> {
    try {
      const queryParams = new URLSearchParams();
      
      // Required params
      queryParams.set('storeId', params.storeId);
      queryParams.set('languageId', params.languageId);
      
      // Pagination params for server-side pagination
      if (params.page) queryParams.set('page', String(params.page));
      if (params.limit) queryParams.set('limit', String(params.limit));
      
      // Optional filters
      if (params.categoryId) queryParams.set('categoryId', params.categoryId);
      if (params.subCategoryId) queryParams.set('subCategoryId', params.subCategoryId);
      if (params.productTypeId) queryParams.set('productTypeId', params.productTypeId);
      if (params.search) queryParams.set('search', params.search);
      if (params.carBrand) queryParams.set('carBrand', params.carBrand);
      if (params.carModel) queryParams.set('carModel', params.carModel);
      // New year-range based filtering
      if (params.carId) queryParams.set('carId', params.carId);
      if (params.carYear) queryParams.set('carYear', String(params.carYear));
      
      const response = await apiClient.get<any>(`/admin/products?${queryParams.toString()}`);

      return parseProductListResponse(response.data, params);
    } catch (error: unknown) {
      console.error('List products error:', error);
      throw new Error(getApiErrorMessage(error, 'Failed to fetch products'));
    }
  }

  /**
   * Get product by ID (admin)
   * GET /api/admin/products/{productId}
   */
  async getProductById(productId: string, languageId: string): Promise<Product> {
    try {
      const response = await apiClient.get<Product>(`/admin/products/${productId}?languageId=${languageId}`);
      return response.data.data;
    } catch (error: any) {
      console.error('Get product error:', error);
      throw new Error(error.response?.data?.error?.message || 'Failed to fetch product details');
    }
  }

  /**
   * Create product (admin)
   * POST /api/admin/products
   */
  async createProduct(productData: CreateProductRequest): Promise<Product> {
    try {
      const response = await apiClient.post<Product>('/admin/products', productData);
      return response.data.data;
    } catch (error: any) {
      console.error('Create product error:', error);
      throw new Error(error.response?.data?.error?.message || 'Failed to create product');
    }
  }

  /**
   * Update product (admin)
   * PUT /api/admin/products/{productId}
   */
  async updateProduct(productId: string, productData: UpdateProductRequest): Promise<Product> {
    try {
      const response = await apiClient.put<Product>(`/admin/products/${productId}`, productData);
      return response.data.data;
    } catch (error: any) {
      console.error('Update product error:', error);
      throw new Error(error.response?.data?.error?.message || 'Failed to update product');
    }
  }

  /**
   * Delete product (admin)
   * DELETE /api/admin/products/{productId}
   */
  async deleteProduct(productId: string): Promise<void> {
    try {
      await apiClient.delete(`/admin/products/${productId}`);
    } catch (error: any) {
      console.error('Delete product error:', error);
      throw new Error(error.response?.data?.error?.message || 'Failed to delete product');
    }
  }
}

export const productService = new ProductService();
